
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int UMINUS = 5;
  public static final int NUMBER = 9;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int TIMES = 6;
  public static final int LPAREN = 7;
  
  public static final int ADD = 10;
  public static final int SUB = 11;
  public static final int MUL = 12;
  public static final int DIV = 13;
	
  public static final int AND = 14;
  public static final int OR = 15;
  public static final int NOT = 16;
	
  public static final int EQUAL = 17;
  public static final int LT = 18;
  public static final int GT = 19;
  public static final int LE = 20;
  public static final int GE = 21;
	
  public static final int ASSIGN = 22;
	
  public static final int LPAR = 23;
  public static final int RPAR = 24;
  public static final int CLPAR = 25;
  public static final int CRPAR = 26;
  public static final int SLPAR = 27;
  public static final int SRPAR = 28;
	
  public static final int COLON = 29;
  public static final int SEMICOLON = 30;
  public static final int COMMA = 31;
	
  public static final int IF = 32;
  public static final int THEN = 33;
  public static final int WHILE = 34;
  public static final int DO = 35;
  public static final int READ = 36;
  public static final int ELSE = 37;
  public static final int BEGIN = 38;
  public static final int END = 39;
  public static final int PRINT = 40;
  public static final int INT = 41;
  public static final int BOOL = 42;
  public static final int REAL = 43;
  public static final int VAR = 44;
  public static final int SIZE = 45;
  public static final int FLOAT = 46;
  public static final int FLOOR = 47;
  public static final int CEIL = 48;
  public static final int FUN = 49;
  public static final int RETURN = 50;
  public static final int SIGM = 51;
  
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "NUMBER"
  };
}

